version: '3.8'

services:
  inventory-app:
    build: .
    container_name: inventory_app_container
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - APP_KEY=base64:TLlloRXRWARw8c33LmT68z6nqPZMkOkh/YepxxDMg5c=
      - APP_ENV=local
      - APP_DEBUG=true
    restart: unless-stopped
